### ISSUE TITLE
Imports editor dll, even if already exists

### ISSUE THREAD

**Issue by citizenmatt** [JetBrains/resharper-unity#489]
If a project already has the editor plugin assembly in the assets folder, but is not at the default location (e.g. it's at `Assets/Plugins/Editor/`) then Rider will attempt to copy another version to `Assets/Plugins/Editor/JetBrains` and the compile will fail.

```
error CS1704: An assembly with the same name `JetBrains.Rider.Unity.Editor.Plugin.Repacked' has already been imported. Consider removing one of the references or sign the assembly
Assets/Plugins/Editor/JetBrains.Rider.Unity.Editor.Plugin.Repacked.dll (Location of the symbol related to previous error)
Assets/Plugins/Editor/JetBrains/JetBrains.Rider.Unity.Editor.Plugin.Repacked.dll (Location of the symbol related to previous error)
```

**Comment by van800** [comment]
Will appear in the recent nightly
https://github.com/JetBrains/resharper-unity/pull/495

**Comment by Baste-RainGames** [comment]
This seems to have regressed, I have moved the .dll to Assets/JetBrains/Editor, but whenever I install a new Rider version, I'm getting a copy in Assets/Plugins/Editor/JetBrains, forcing me to remove the old one and copy over the new one.

**Comment by van800** [comment]
@Baste-RainGames What version have you tried?

**Comment by Baste-RainGames** [comment]
What had me report the bug now was going from Rider 2018.2 to 2018.3 EAP 4. The same thing happened when I tried to use EAP2 before having to give up on it due to an unrelated bug (that's fixed now!). 
I'm _fairly certain_ it was an issue during the 2018.2 EAP cycle and when updating to 2018.2, but that's a while ago. 

The plugin version is 2018.3.0.28, but it seems to automatically update with Rider, so I guess that's a given?
